const TEST_HTML = `
<h1 id="firstHeading" class="firstHeading mw-first-heading">
    <span class="mw-page-title-main">Nico Ditch</span>
 </h1>
 <div class="mw-content-ltr mw-parser-output" lang="en" dir="ltr">
    <div class="shortdescription nomobile noexcerpt noprint searchaux" style="display:none">Earthwork in England</div>
    <p class="mw-empty-elt">
    </p>
    <style data-mw-deduplicate="TemplateStyles:r1237879389">.mw-parser-output .infobox-subbox{padding:0;border:none;margin:-3px;width:auto;min-width:100%;font-size:100%;clear:none;float:none;background-color:transparent}.mw-parser-output .infobox-3cols-child{margin:auto}.mw-parser-output .infobox .navbar{font-size:100%}body.skin-minerva .mw-parser-output .infobox-header,body.skin-minerva .mw-parser-output .infobox-subheader,body.skin-minerva .mw-parser-output .infobox-above,body.skin-minerva .mw-parser-output .infobox-title,body.skin-minerva .mw-parser-output .infobox-image,body.skin-minerva .mw-parser-output .infobox-full-data,body.skin-minerva .mw-parser-output .infobox-below{text-align:center}@media screen{html.skin-theme-clientpref-night .mw-parser-output .infobox-full-data:not(.notheme)>div:not(.notheme)[style]{background:#1f1f23!important;color:#f8f9fa}}@media screen and (prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .infobox-full-data:not(.notheme) div:not(.notheme){background:#1f1f23!important;color:#f8f9fa}}@media(min-width:640px){body.skin--responsive .mw-parser-output .infobox-table{display:table!important}body.skin--responsive .mw-parser-output .infobox-table>caption{display:table-caption!important}body.skin--responsive .mw-parser-output .infobox-table>tbody{display:table-row-group}body.skin--responsive .mw-parser-output .infobox-table tr{display:table-row!important}body.skin--responsive .mw-parser-output .infobox-table th,body.skin--responsive .mw-parser-output .infobox-table td{padding-left:inherit;padding-right:inherit}}</style>
    <p><b>Nico Ditch</b> is a six-mile (9.7&nbsp;km) long linear <a href="/wiki/Earthworks_(archaeology)" title="Earthworks (archaeology)">earthwork</a> between <a href="/wiki/Ashton-under-Lyne" title="Ashton-under-Lyne">Ashton-under-Lyne</a> and <a href="/wiki/Stretford" title="Stretford">Stretford</a> in Greater Manchester, England. It was dug as a defensive fortification, or possibly a boundary marker, between the 5th and 11th century. The ditch is still visible in short sections, such as a 330-yard (300&nbsp;m) stretch in <a href="/wiki/Denton,_Greater_Manchester" title="Denton, Greater Manchester">Denton</a> Golf Course. For the parts which survived, the ditch is 4–5 yards (3.7–4.6&nbsp;m) wide and up to 5 feet (1.5&nbsp;m) deep. Part of the earthwork is protected as a <a href="/wiki/Scheduled_Ancient_Monument" class="mw-redirect" title="Scheduled Ancient Monument">Scheduled Ancient Monument</a>.</p>
    <meta property="mw:PageProp/toc">
    <div class="mw-heading mw-heading2">
       <h2 id="Etymology">Etymology</h2>
       <span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Nico_Ditch&amp;action=edit&amp;section=1" title="Edit section: Etymology"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span>
    </div>
    <p>The earliest documented reference to the ditch is in a charter detailing the granting of land in <a href="/wiki/Audenshaw" title="Audenshaw">Audenshaw</a> to the monks of the <a href="/wiki/Kersal" title="Kersal">Kersal Cell</a>. In the document, dating from 1190&nbsp;to&nbsp;1212, the ditch is referred to as "Mykelldiche", and a <i>magnum fossatum</i>, which is Latin for "large ditch".<sup id="cite_ref-N92_78_1-0" class="reference"><a href="#cite_note-N92_78-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup></p>
    <p>The name Nico (sometimes Nikker) for the ditch became established in the 19th and 20th century. It may have been derived from the <a href="/wiki/Old_English" title="Old English">Anglo-Saxon</a> <i><a href="/wiki/Nickar" class="mw-redirect" title="Nickar">Hnickar</a></i>, a water spirit who seized and drowned unwary travellers, but the modern name is most likely a corruption of the name Mykelldiche and its variations; this is because the Anglo-Saxon word <i>micel</i> means "big" or "great", harking back to the early 13th century description of the ditch as <i>magnum fossatum</i>.<sup id="cite_ref-N92_78_1-1" class="reference"><a href="#cite_note-N92_78-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup> An alternative derivation of Nico comes from <i>nǽcan</i>, an Anglo-Saxon verb meaning "kill".<sup id="cite_ref-2" class="reference"><a href="#cite_note-2"><span class="cite-bracket">[</span>2<span class="cite-bracket">]</span></a></sup></p>
    <div class="mw-heading mw-heading2">
       <h2 id="Course">Course</h2>
       <span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Nico_Ditch&amp;action=edit&amp;section=2" title="Edit section: Course"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span>
    </div>
    <p>
       Nico Ditch stretches 6&nbsp;mi (9.7&nbsp;km) between Ashton Moss (<a href="/wiki/Ordnance_Survey_National_Grid" title="Ordnance Survey National Grid">grid reference</a> 
       <span class="plainlinks nourlexpansion" style="white-space: nowrap">
          <span style="position: relative; white-space: nowrap;">
    <div style="background-color: white; padding: 0.2em; border: 1px solid black; position: absolute; top: 1em; left: 0em; display: none; z-index: 15;"><span style="cursor: pointer;"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/17px-WMA_button2b.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/17px-WMA_button2b.png 1x, //upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/34px-WMA_button2b.png 2x" class="wmamapbutton noprint" title="Show location on an interactive map" alt="" style="padding: 0px 3px 0px 0px; cursor: pointer;">&nbsp;WikiMiniAtlas</span></div><a class="external text" href="https://geohack.toolforge.org/geohack.php?pagename=Nico_Ditch&amp;params=53.478645_N_2.138582_W_region:GB_scale:25000">SJ909980</a></span></span>) in Ashton-under-Lyne and Hough Moss (<a href="/wiki/Ordnance_Survey_National_Grid" title="Ordnance Survey National Grid">grid reference</a> 
    <span class="plainlinks nourlexpansion" style="white-space: nowrap">
       <span style="position: relative; white-space: nowrap;">
          <div style="background-color: white; padding: 0.2em; border: 1px solid black; position: absolute; top: 1em; left: 0em; display: none; z-index: 15;"><span style="cursor: pointer;"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/17px-WMA_button2b.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/17px-WMA_button2b.png 1x, //upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/34px-WMA_button2b.png 2x" class="wmamapbutton noprint" title="Show location on an interactive map" alt="" style="padding: 0px 3px 0px 0px; cursor: pointer;">&nbsp;WikiMiniAtlas</span></div>
          <a class="external text" href="https://geohack.toolforge.org/geohack.php?pagename=Nico_Ditch&amp;params=53.450667_N_2.260308_W_region:GB_scale:25000">SJ82819491</a>
       </span>
    </span>
    ), which is just east of <a href="/wiki/Stretford" title="Stretford">Stretford</a>.<sup id="cite_ref-Lands_and_Lordships_3-0" class="reference"><a href="#cite_note-Lands_and_Lordships-3"><span class="cite-bracket">[</span>3<span class="cite-bracket">]</span></a></sup> It passes through <a href="/wiki/Denton,_Greater_Manchester" title="Denton, Greater Manchester">Denton</a>, <a href="/wiki/Reddish" title="Reddish">Reddish</a>, <a href="/wiki/Gorton" title="Gorton">Gorton</a>, <a href="/wiki/Levenshulme" title="Levenshulme">Levenshulme</a>, <a href="/wiki/Burnage" title="Burnage">Burnage</a>, <a href="/wiki/Rusholme" title="Rusholme">Rusholme</a>, <a href="/wiki/Platt_Fields_Park" title="Platt Fields Park">Platt Fields Park</a> in <a href="/wiki/Fallowfield" title="Fallowfield">Fallowfield</a>, <a href="/wiki/Withington" title="Withington">Withington</a> and <a href="/wiki/Chorlton-cum-Hardy" title="Chorlton-cum-Hardy">Chorlton-cum-Hardy</a>, crossing four <a href="/wiki/Metropolitan_borough" title="Metropolitan borough">metropolitan boroughs</a> of present-day <a href="/wiki/Greater_Manchester" title="Greater Manchester">Greater Manchester</a>. The ditch coincides with the boundaries between the boroughs of <a href="/wiki/Metropolitan_Borough_of_Stockport" title="Metropolitan Borough of Stockport">Stockport</a> and <a href="/wiki/Manchester" title="Manchester">Manchester</a>, and between Tameside and Manchester; it reaches as far as the Denton golf course. A section is now beneath the <a href="/wiki/Audenshaw_Reservoirs" title="Audenshaw Reservoirs">Audenshaw Reservoirs</a>, which were built towards the end of the 19th century.<sup id="cite_ref-4" class="reference"><a href="#cite_note-4"><span class="cite-bracket">[</span>4<span class="cite-bracket">]</span></a></sup> The ditch may have extended west beyond Stretford, to <a href="/wiki/Urmston" title="Urmston">Urmston</a> (<a href="/wiki/Ordnance_Survey_National_Grid" title="Ordnance Survey National Grid">grid reference</a> 
    <span class="plainlinks nourlexpansion" style="white-space: nowrap">
       <span style="position: relative; white-space: nowrap;">
          <div style="background-color: white; padding: 0.2em; border: 1px solid black; position: absolute; top: 1em; left: 0em; display: none; z-index: 15;"><span style="cursor: pointer;"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/17px-WMA_button2b.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/17px-WMA_button2b.png 1x, //upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/34px-WMA_button2b.png 2x" class="wmamapbutton noprint" title="Show location on an interactive map" alt="" style="padding: 0px 3px 0px 0px; cursor: pointer;">&nbsp;WikiMiniAtlas</span></div>
          <a class="external text" href="https://geohack.toolforge.org/geohack.php?pagename=Nico_Ditch&amp;params=53.451668_N_2.328376_W_region:GB_scale:25000">SJ78299504</a>
       </span>
    </span>
    ).<sup id="cite_ref-N92_78_1-2" class="reference"><a href="#cite_note-N92_78-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup>
    </p>
    <div class="mw-heading mw-heading2">
       <h2 id="History">History</h2>
       <span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Nico_Ditch&amp;action=edit&amp;section=3" title="Edit section: History"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span>
    </div>
    <p>The earthwork was constructed some time between the <a href="/wiki/End_of_Roman_rule_in_Britain" title="End of Roman rule in Britain">end of Roman rule in Britain</a> in the early 5th century and the <a href="/wiki/Norman_conquest_of_England" class="mw-redirect" title="Norman conquest of England">Norman conquest</a> in 1066. Its original purpose is unclear, but it may have been used as a defensive fortification or as an administrative boundary. It possibly marked a 7th-century boundary for the expansionist <a href="/wiki/Anglo-Saxons" title="Anglo-Saxons">Anglo-Saxons</a>, or it may have been a late 8th or early 9th century boundary marker between the kingdoms of <a href="/wiki/Mercia" title="Mercia">Mercia</a> and <a href="/wiki/Northumbria" title="Northumbria">Northumbria</a>.<sup id="cite_ref-N_92_83_5-0" class="reference"><a href="#cite_note-N_92_83-5"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup> In the <a href="/wiki/Early_medieval" class="mw-redirect" title="Early medieval">early medieval</a> period, the Anglo-Saxon kingdoms of Northumbria, Mercia, and <a href="/wiki/Wessex" title="Wessex">Wessex</a> struggled for control over <a href="/wiki/North_West_England" title="North West England">North West England</a>,<sup id="cite_ref-6" class="reference"><a href="#cite_note-6"><span class="cite-bracket">[</span>6<span class="cite-bracket">]</span></a></sup> along with the <a href="/wiki/Britons_(historical)" class="mw-redirect" title="Britons (historical)">Britons</a> and the <a href="/wiki/Danes_(Germanic_tribe)" class="mw-redirect" title="Danes (Germanic tribe)">Danes</a>. Whatever its earlier use, the ditch has been used as a boundary since at least the <a href="/wiki/Middle_Ages" title="Middle Ages">Middle Ages</a>.<sup id="cite_ref-7" class="reference"><a href="#cite_note-7"><span class="cite-bracket">[</span>7<span class="cite-bracket">]</span></a></sup></p>
    <p>Legend has it Nico Ditch was completed in a single night by the inhabitants of Manchester, as a protection against Viking invaders in 869–870; Manchester may have been <a href="/wiki/Looting" title="Looting">sacked</a> by the Danes in 870.<sup id="cite_ref-8" class="reference"><a href="#cite_note-8"><span class="cite-bracket">[</span>8<span class="cite-bracket">]</span></a></sup> It was said that each man had an allocated area to construct, and was required to dig his section of the ditch and build a bank equal to his own height.<sup id="cite_ref-N_92_83_5-1" class="reference"><a href="#cite_note-N_92_83-5"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup> According to 19th century folklore, the ditch was the site of a battle between <a href="/wiki/Saxons" title="Saxons">Saxons</a> and Danes. The battle was supposed to have given the nearby towns of Gorton and Reddish their names, from "Gore Town" and "Red-Ditch", respectively, <sup id="cite_ref-9" class="reference"><a href="#cite_note-9"><span class="cite-bracket">[</span>9<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-10" class="reference"><a href="#cite_note-10"><span class="cite-bracket">[</span>10<span class="cite-bracket">]</span></a></sup> but the idea has been dismissed by historians as a "popular fancy".<sup id="cite_ref-11" class="reference"><a href="#cite_note-11"><span class="cite-bracket">[</span>11<span class="cite-bracket">]</span></a></sup> The names derive from "dirty farmstead" and "reedy ditch" respectively.<sup id="cite_ref-12" class="reference"><a href="#cite_note-12"><span class="cite-bracket">[</span>12<span class="cite-bracket">]</span></a></sup></p>
    <p><a href="/wiki/Antiquarian" title="Antiquarian">Antiquarians</a> and historians have been interested in the ditch since the 19th century, but much of its course has been built over. Between 1990 and 1997, the University of Manchester Archaeological Unit excavated sections of the ditch in Denton, Reddish, Levenshulme, and Platt Fields, in an attempt to determine its age and purpose. Although no date was established for the ditch's construction, the investigations revealed that the bank to the north of the ditch is of 20th century origin. Together with the ditch's profile, which is U-shaped rather than the V-shape typically used in military ditches and defenses, this suggests that the purpose of the earthwork was to mark a territorial boundary.<sup id="cite_ref-Lands_and_Lordships_3-1" class="reference"><a href="#cite_note-Lands_and_Lordships-3"><span class="cite-bracket">[</span>3<span class="cite-bracket">]</span></a></sup> The conclusion of the project was that the ditch was probably a boundary marker.<sup id="cite_ref-13" class="reference"><a href="#cite_note-13"><span class="cite-bracket">[</span>13<span class="cite-bracket">]</span></a></sup></p>
    <div class="mw-heading mw-heading2">
       <h2 id="Preservation">Preservation</h2>
       <span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Nico_Ditch&amp;action=edit&amp;section=4" title="Edit section: Preservation"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span>
    </div>
    <p>Despite heavy weathering, the ditch is still visible in short sections, which can be up to 4–5 yards (3.7–4.6&nbsp;m) wide and up to 5 feet (1.5&nbsp;m) deep. A 330-yard (300&nbsp;m) stretch through <a href="/wiki/Denton,_Greater_Manchester" title="Denton, Greater Manchester">Denton</a> Golf Course, and a section running through <a href="/wiki/Platt_Fields_Park" title="Platt Fields Park">Platt Fields Park</a>, are considered the best preserved remains.<sup id="cite_ref-14" class="reference"><a href="#cite_note-14"><span class="cite-bracket">[</span>14<span class="cite-bracket">]</span></a></sup><sup id="cite_ref-15" class="reference"><a href="#cite_note-15"><span class="cite-bracket">[</span>15<span class="cite-bracket">]</span></a></sup> In 1997, a 150-yard (140&nbsp;m) segment of the ditch in Platt Fields was protected as a <a href="/wiki/Scheduled_Ancient_Monument" class="mw-redirect" title="Scheduled Ancient Monument">Scheduled Ancient Monument</a>. The rest of the ditch remains unprotected.<sup id="cite_ref-Nico_Ditch_16-0" class="reference"><a href="#cite_note-Nico_Ditch-16"><span class="cite-bracket">[</span>16<span class="cite-bracket">]</span></a></sup></p>
    <div class="mw-heading mw-heading2">
       <h2 id="See_also">See also</h2>
       <span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Nico_Ditch&amp;action=edit&amp;section=5" title="Edit section: See also"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span>
    </div>
    <ul>
       <li><a href="/wiki/History_of_Manchester" title="History of Manchester">History of Manchester</a></li>
       <li><a href="/wiki/Scheduled_Monuments_in_Greater_Manchester" class="mw-redirect" title="Scheduled Monuments in Greater Manchester">Scheduled Monuments in Greater Manchester</a></li>
    </ul>
    <div class="mw-heading mw-heading2">
       <h2 id="References">References</h2>
       <span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Nico_Ditch&amp;action=edit&amp;section=6" title="Edit section: References"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span>
    </div>
    <style data-mw-deduplicate="TemplateStyles:r1239543626">.mw-parser-output .reflist{margin-bottom:0.5em;list-style-type:decimal}@media screen{.mw-parser-output .reflist{font-size:90%}}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}</style>
    <div class="reflist">
       <div class="mw-references-wrap mw-references-columns">
          <ol class="references">
             <li id="cite_note-N92_78-1"><span class="mw-cite-backlink">^ <a href="#cite_ref-N92_78_1-0"><span class="cite-accessibility-label">Jump up to: </span><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-N92_78_1-1"><sup><i><b>b</b></i></sup></a> <a href="#cite_ref-N92_78_1-2"><sup><i><b>c</b></i></sup></a></span> <span class="reference-text">Nevell (1992), p.&nbsp;78.</span></li>
             <li id="cite_note-2">
                <span class="mw-cite-backlink"><b><a href="#cite_ref-2" aria-label="Jump up" title="Jump up">^</a></b></span> 
                <span class="reference-text">
                   <style data-mw-deduplicate="TemplateStyles:r1238218222">.mw-parser-output cite.citation{font-style:inherit;word-wrap:break-word}.mw-parser-output .citation q{quotes:"\"""\"""'""'"}.mw-parser-output .citation:target{background-color:rgba(0,127,255,0.133)}.mw-parser-output .id-lock-free.id-lock-free a{background:url("//upload.wikimedia.org/wikipedia/commons/6/65/Lock-green.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-limited.id-lock-limited a,.mw-parser-output .id-lock-registration.id-lock-registration a{background:url("//upload.wikimedia.org/wikipedia/commons/d/d6/Lock-gray-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-subscription.id-lock-subscription a{background:url("//upload.wikimedia.org/wikipedia/commons/a/aa/Lock-red-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .cs1-ws-icon a{background:url("//upload.wikimedia.org/wikipedia/commons/4/4c/Wikisource-logo.svg")right 0.1em center/12px no-repeat}body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-free a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-limited a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-registration a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .id-lock-subscription a,body:not(.skin-timeless):not(.skin-minerva) .mw-parser-output .cs1-ws-icon a{background-size:contain;padding:0 1em 0 0}.mw-parser-output .cs1-code{color:inherit;background:inherit;border:none;padding:inherit}.mw-parser-output .cs1-hidden-error{display:none;color:var(--color-error,#d33)}.mw-parser-output .cs1-visible-error{color:var(--color-error,#d33)}.mw-parser-output .cs1-maint{display:none;color:#085;margin-left:0.3em}.mw-parser-output .cs1-kern-left{padding-left:0.2em}.mw-parser-output .cs1-kern-right{padding-right:0.2em}.mw-parser-output .citation .mw-selflink{font-weight:inherit}@media screen{.mw-parser-output .cs1-format{font-size:95%}html.skin-theme-clientpref-night .mw-parser-output .cs1-maint{color:#18911f}}@media screen and (prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .cs1-maint{color:#18911f}}</style>
                   <cite id="CITEREFBased_on_the_manuscript_collections_of_the_late_Joseph_Bosworth,_D.D._F.R.S1998" class="citation web cs1">Based on the manuscript collections of the late Joseph Bosworth, D.D. F.R.S (1998). <a rel="nofollow" class="external text" href="https://web.archive.org/web/20110708085401/http://bosworthandtoller.com/read.htm?page_nr=706">"Online Anglo-Saxon dictionary"</a>. <a href="/wiki/Clarendon_Press" class="mw-redirect" title="Clarendon Press">Clarendon Press</a>. Archived from <a rel="nofollow" class="external text" href="http://bosworthandtoller.com/read.htm?page_nr=706">the original</a> on 8 July 2011<span class="reference-accessdate">. Retrieved <span class="nowrap">25 August</span> 2007</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=unknown&amp;rft.btitle=Online+Anglo-Saxon+dictionary&amp;rft.pub=Clarendon+Press&amp;rft.date=1998&amp;rft.au=Based+on+the+manuscript+collections+of+the+late+Joseph+Bosworth%2C+D.D.+F.R.S&amp;rft_id=http%3A%2F%2Fbosworthandtoller.com%2Fread.htm%3Fpage_nr%3D706&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
                </span>
             </li>
             <li id="cite_note-Lands_and_Lordships-3"><span class="mw-cite-backlink">^ <a href="#cite_ref-Lands_and_Lordships_3-0"><span class="cite-accessibility-label">Jump up to: </span><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-Lands_and_Lordships_3-1"><sup><i><b>b</b></i></sup></a></span> <span class="reference-text">Nevell (1998), p.&nbsp;40.</span></li>
             <li id="cite_note-4"><span class="mw-cite-backlink"><b><a href="#cite_ref-4" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Nevell (1992), p.&nbsp;81.</span></li>
             <li id="cite_note-N_92_83-5"><span class="mw-cite-backlink">^ <a href="#cite_ref-N_92_83_5-0"><span class="cite-accessibility-label">Jump up to: </span><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-N_92_83_5-1"><sup><i><b>b</b></i></sup></a></span> <span class="reference-text">Nevell (1992), p.&nbsp;83.</span></li>
             <li id="cite_note-6"><span class="mw-cite-backlink"><b><a href="#cite_ref-6" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Hylton (2003), p.&nbsp;7.</span></li>
             <li id="cite_note-7"><span class="mw-cite-backlink"><b><a href="#cite_ref-7" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Nevell (1992), pp.&nbsp;82–83.</span></li>
             <li id="cite_note-8"><span class="mw-cite-backlink"><b><a href="#cite_ref-8" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Hylton (2003), p.&nbsp;8.</span></li>
             <li id="cite_note-9"><span class="mw-cite-backlink"><b><a href="#cite_ref-9" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Booker (1857), p.&nbsp;197.</span></li>
             <li id="cite_note-10"><span class="mw-cite-backlink"><b><a href="#cite_ref-10" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Harland &amp; Wilkinson (1993), pp.&nbsp;26–29.</span></li>
             <li id="cite_note-11"><span class="mw-cite-backlink"><b><a href="#cite_ref-11" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Farrer &amp; Brownbill (1911), pp.&nbsp;275–279.</span></li>
             <li id="cite_note-12">
                <span class="mw-cite-backlink"><b><a href="#cite_ref-12" aria-label="Jump up" title="Jump up">^</a></b></span> 
                <span class="reference-text">
                   <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222">
                   <cite class="citation web cs1"><a rel="nofollow" class="external text" href="https://www.bbc.co.uk/manchester/content/articles/2008/08/01/010808_nico_ditch_feature.shtml">"A ditch in time"</a>. <a href="/wiki/BBC" title="BBC">BBC</a>. 1 August 2008. <a rel="nofollow" class="external text" href="https://web.archive.org/web/20191219060135/http://www.bbc.co.uk/manchester/content/articles/2008/08/01/010808_nico_ditch_feature.shtml">Archived</a> from the original on 19 December 2019<span class="reference-accessdate">. Retrieved <span class="nowrap">24 December</span> 2019</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=unknown&amp;rft.btitle=A+ditch+in+time&amp;rft.pub=BBC&amp;rft.date=2008-08-01&amp;rft_id=https%3A%2F%2Fwww.bbc.co.uk%2Fmanchester%2Fcontent%2Farticles%2F2008%2F08%2F01%2F010808_nico_ditch_feature.shtml&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
                </span>
             </li>
             <li id="cite_note-13"><span class="mw-cite-backlink"><b><a href="#cite_ref-13" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Nevell (1998), p.&nbsp;41.</span></li>
             <li id="cite_note-14"><span class="mw-cite-backlink"><b><a href="#cite_ref-14" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Nevell (1992), p.&nbsp;79.</span></li>
             <li id="cite_note-15"><span class="mw-cite-backlink"><b><a href="#cite_ref-15" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text">Nevell (2008), p.&nbsp;39.</span></li>
             <li id="cite_note-Nico_Ditch-16">
                <span class="mw-cite-backlink"><b><a href="#cite_ref-Nico_Ditch_16-0" aria-label="Jump up" title="Jump up">^</a></b></span> 
                <span class="reference-text">
                   <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222">
                   <cite id="CITEREFHistoric_England1033812" class="citation web cs1"><a href="/wiki/Historic_England" title="Historic England">Historic England</a>. <a rel="nofollow" class="external text" href="https://www.heritagegateway.org.uk/Gateway/Results_Single.aspx?uid=1033812&amp;resourceID=19191">"Nico Ditch  (1033812)"</a>. <i>Research records (formerly PastScape)</i><span class="reference-accessdate">. Retrieved <span class="nowrap">30 December</span> 2007</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=unknown&amp;rft.jtitle=Research+records+%28formerly+PastScape%29&amp;rft.atitle=Nico+Ditch+%281033812%29&amp;rft.au=Historic+England&amp;rft_id=https%3A%2F%2Fwww.heritagegateway.org.uk%2FGateway%2FResults_Single.aspx%3Fuid%3D1033812%26resourceID%3D19191&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
                </span>
             </li>
          </ol>
       </div>
    </div>
    <div class="mw-heading mw-heading3">
       <h3 id="Bibliography">Bibliography</h3>
       <span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Nico_Ditch&amp;action=edit&amp;section=7" title="Edit section: Bibliography"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span>
    </div>
    <style data-mw-deduplicate="TemplateStyles:r1239549316">.mw-parser-output .refbegin{margin-bottom:0.5em}.mw-parser-output .refbegin-hanging-indents>ul{margin-left:0}.mw-parser-output .refbegin-hanging-indents>ul>li{margin-left:0;padding-left:3.2em;text-indent:-3.2em}.mw-parser-output .refbegin-hanging-indents ul,.mw-parser-output .refbegin-hanging-indents ul li{list-style:none}@media(max-width:720px){.mw-parser-output .refbegin-hanging-indents>ul>li{padding-left:1.6em;text-indent:-1.6em}}.mw-parser-output .refbegin-columns{margin-top:0.3em}.mw-parser-output .refbegin-columns ul{margin-top:0}.mw-parser-output .refbegin-columns li{page-break-inside:avoid;break-inside:avoid-column}@media screen{.mw-parser-output .refbegin{font-size:90%}}</style>
    <div class="refbegin" style="">
       <ul>
          <li>
             <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222">
             <cite id="CITEREFBooker1857" class="citation book cs1">Booker, John (1857). <a rel="nofollow" class="external text" href="https://archive.org/details/ahistoryancient01bookgoog"><i>A history of the ancient chapels of Didsbury and Chorlton</i></a>. Manchester: Chethams.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=A+history+of+the+ancient+chapels+of+Didsbury+and+Chorlton&amp;rft.place=Manchester&amp;rft.pub=Chethams&amp;rft.date=1857&amp;rft.aulast=Booker&amp;rft.aufirst=John&amp;rft_id=https%3A%2F%2Farchive.org%2Fdetails%2Fahistoryancient01bookgoog&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
          </li>
          <li>
             <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222">
             <cite id="CITEREFFarrer,_WBrownbill,_J1911" class="citation journal cs1">Farrer, W; Brownbill, J, eds. (1911). <a rel="nofollow" class="external text" href="http://www.british-history.ac.uk/report.aspx?compid=41420">"Townships: Gorton"</a>. <i>A History of the County of Lancaster</i>. <b>4</b>: 275–279. <a rel="nofollow" class="external text" href="https://web.archive.org/web/20110526035323/http://www.british-history.ac.uk/report.aspx?compid=41420">Archived</a> from the original on 26 May 2011<span class="reference-accessdate">. Retrieved <span class="nowrap">5 January</span> 2009</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.jtitle=A+History+of+the+County+of+Lancaster&amp;rft.atitle=Townships%3A+Gorton&amp;rft.volume=4&amp;rft.pages=275-279&amp;rft.date=1911&amp;rft_id=http%3A%2F%2Fwww.british-history.ac.uk%2Freport.aspx%3Fcompid%3D41420&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
          </li>
          <li>
             <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222">
             <cite id="CITEREFHarlandWilkinson,_Thomas_Turner1993" class="citation book cs1"><a href="/wiki/John_Harland" title="John Harland">Harland, John</a>; Wilkinson, Thomas Turner (1993) [1873]. <i>Lancashire Legends, Traditions</i>. Llanerch Press. <a href="/wiki/ISBN_(identifier)" class="mw-redirect" title="ISBN (identifier)">ISBN</a>&nbsp;<a href="/wiki/Special:BookSources/1-897853-06-8" title="Special:BookSources/1-897853-06-8"><bdi>1-897853-06-8</bdi></a>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Lancashire+Legends%2C+Traditions&amp;rft.pub=Llanerch+Press&amp;rft.date=1993&amp;rft.isbn=1-897853-06-8&amp;rft.aulast=Harland&amp;rft.aufirst=John&amp;rft.au=Wilkinson%2C+Thomas+Turner&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
          </li>
          <li>
             <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222">
             <cite id="CITEREFHylton2003" class="citation book cs1">Hylton, Stuart (2003). <i>A History of Manchester</i>. Chichester: Phillimore and Co. Ltd. <a href="/wiki/ISBN_(identifier)" class="mw-redirect" title="ISBN (identifier)">ISBN</a>&nbsp;<a href="/wiki/Special:BookSources/1-86077-240-4" title="Special:BookSources/1-86077-240-4"><bdi>1-86077-240-4</bdi></a>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=A+History+of+Manchester&amp;rft.place=Chichester&amp;rft.pub=Phillimore+and+Co.+Ltd.&amp;rft.date=2003&amp;rft.isbn=1-86077-240-4&amp;rft.aulast=Hylton&amp;rft.aufirst=Stuart&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
          </li>
          <li>
             <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222">
             <cite id="CITEREFNevell1992" class="citation book cs1">Nevell, Mike (1992). <i>Tameside Before 1066</i>. Tameside Metropolitan Borough Council. <a href="/wiki/ISBN_(identifier)" class="mw-redirect" title="ISBN (identifier)">ISBN</a>&nbsp;<a href="/wiki/Special:BookSources/1-871324-07-6" title="Special:BookSources/1-871324-07-6"><bdi>1-871324-07-6</bdi></a>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Tameside+Before+1066&amp;rft.pub=Tameside+Metropolitan+Borough+Council&amp;rft.date=1992&amp;rft.isbn=1-871324-07-6&amp;rft.aulast=Nevell&amp;rft.aufirst=Mike&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
          </li>
          <li>
             <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222">
             <cite id="CITEREFNevell1998" class="citation book cs1">Nevell, Mike (1998). <i>Lands and Lordships in Tameside</i>. Tameside Metropolitan Borough Council with the <a href="/wiki/Manchester_University" class="mw-redirect" title="Manchester University">University of Manchester Archaeological Unit</a>. <a href="/wiki/ISBN_(identifier)" class="mw-redirect" title="ISBN (identifier)">ISBN</a>&nbsp;<a href="/wiki/Special:BookSources/1-871324-18-1" title="Special:BookSources/1-871324-18-1"><bdi>1-871324-18-1</bdi></a>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Lands+and+Lordships+in+Tameside&amp;rft.pub=Tameside+Metropolitan+Borough+Council+with+the+University+of+Manchester+Archaeological+Unit&amp;rft.date=1998&amp;rft.isbn=1-871324-18-1&amp;rft.aulast=Nevell&amp;rft.aufirst=Mike&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
          </li>
          <li>
             <link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1238218222">
             <cite id="CITEREFNevell2008" class="citation book cs1">Nevell, Mike (2008). <i>Manchester: The Hidden History</i>. The History Press. <a href="/wiki/ISBN_(identifier)" class="mw-redirect" title="ISBN (identifier)">ISBN</a>&nbsp;<a href="/wiki/Special:BookSources/978-0-7524-4704-9" title="Special:BookSources/978-0-7524-4704-9"><bdi>978-0-7524-4704-9</bdi></a>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Manchester%3A+The+Hidden+History&amp;rft.pub=The+History+Press&amp;rft.date=2008&amp;rft.isbn=978-0-7524-4704-9&amp;rft.aulast=Nevell&amp;rft.aufirst=Mike&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ANico+Ditch" class="Z3988"></span>
          </li>
       </ul>
    </div>
    <div class="mw-heading mw-heading2">
       <h2 id="External_links">External links</h2>
       <span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Nico_Ditch&amp;action=edit&amp;section=8" title="Edit section: External links"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span>
    </div>
    <style data-mw-deduplicate="TemplateStyles:r1235611614">.mw-parser-output .spoken-wikipedia{border:1px solid #a2a9b1;background-color:var(--background-color-interactive-subtle,#f8f9fa);margin:0.5em 0;padding:0.2em;line-height:1.5em;font-size:90%}.mw-parser-output .spoken-wikipedia-header{text-align:center}.mw-parser-output .spoken-wikipedia-listen-to{font-weight:bold}.mw-parser-output .spoken-wikipedia-files{text-align:center;margin-top:10px;margin-bottom:0.4em}.mw-parser-output .spoken-wikipedia-icon{float:left;margin-left:5px;margin-top:10px}.mw-parser-output .spoken-wikipedia-disclaimer{margin-left:60px;margin-top:10px;font-size:95%;line-height:1.4em}.mw-parser-output .spoken-wikipedia-footer{margin-top:10px;text-align:center}@media(min-width:720px){.mw-parser-output .spoken-wikipedia{width:20em;float:right;clear:right;margin-left:1em}}</style>
    <div class="spoken-wikipedia noprint haudio">
       <div class="spoken-wikipedia-header"><span class="spoken-wikipedia-listen-to">Listen to this article</span> (<span class="duration"><span class="min">8</span> minutes</span>)</div>
       <div class="spoken-wikipedia-files">
       </div>
       <div class="spoken-wikipedia-icon"><span typeof="mw:File"><span title="Spoken Wikipedia"><img alt="Spoken Wikipedia icon" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sound-icon.svg/45px-Sound-icon.svg.png" decoding="async" width="45" height="34" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sound-icon.svg/68px-Sound-icon.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sound-icon.svg/90px-Sound-icon.svg.png 2x" data-file-width="128" data-file-height="96"></span></span></div>
       <div class="spoken-wikipedia-disclaimer"><a href="/wiki/File:En-Nico_Ditch-article.ogg" title="File:En-Nico Ditch-article.ogg">This audio file</a> was created from a revision of this article dated 26&nbsp;May&nbsp;2023<span style="display:none">&nbsp;(<span class="bday dtstart published updated itvstart">2023-05-26</span>)</span>, and does not reflect subsequent edits.</div>
       <div class="spoken-wikipedia-footer">(<a href="/wiki/Wikipedia:Media_help" class="mw-redirect" title="Wikipedia:Media help">Audio help</a>&nbsp;· <a href="/wiki/Wikipedia:Spoken_articles" title="Wikipedia:Spoken articles">More spoken articles</a>)</div>
    </div>
    <ul>
       <li><span class="noviewer" typeof="mw:File"><a href="/wiki/File:Commons-logo.svg" class="mw-file-description"><img alt="" src="//upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/12px-Commons-logo.svg.png" decoding="async" width="12" height="16" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/18px-Commons-logo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/24px-Commons-logo.svg.png 2x" data-file-width="1024" data-file-height="1376"></a></span> Media related to <a href="https://commons.wikimedia.org/wiki/Category:Nico_Ditch" class="extiw" title="commons:Category:Nico Ditch">Nico Ditch</a> at Wikimedia Commons</li>
    </ul>
    <p class="mw-empty-elt"></p>
 </div>
`;
module.exports = TEST_HTML;
